
project:
  type: website
  title: "Yasuki Kudo"
  render:
  - index.qmd

title-block-banner: true
title: "\u200B"
subtitle: ""

website:
  navbar:
    collapse: true
    pinned: true
    background: dark
    left:
      - text: "publications"
        href: "#publications"
      - text: "in progress"
        href: "#in-progress"
      - text: "teaching"
        href: "#teaching"

format:
  html:
    page-layout: full
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    include-before-body: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
editor: visual
